myName = input("Whats your name: ")
myAge = input("How old are you?: ")
print("Gee that is awesome")
reading = input("Do you like reading?: ") 
print("OF COURSE YOU DO")
print()
print("So, you are ")
print(myName)
print("and you have a simple name: ")
print(myAge)
print("andyou don't look your age")
print(reading)
